name: VPN Auto Update
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update_gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install Xray
        # Официальный скрипт установки, работающий в среде Ubuntu
        run: curl -L https://github.com | sudo bash -s -- install

      - run: pip install requests
      - name: Run script
        env:
          GH_TOKEN: ${{ secrets.GIST_TOKEN }}
          MY_GIST_ID: ${{ secrets.MY_GIST_ID }}
        run: python main.py
