name: VPN Auto Update

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update_gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Xray-core
        run: |
          # Пробуем пробить DNS
          sleep 5
          # Качаем скрипт напрямую с правильного домена
          curl -L https://githubusercontent.com -o install.sh
          sudo bash install.sh install
          xray version

      - name: Install Python dependencies
        run: pip install requests

      - name: Run main script
        env:
          GH_TOKEN: ${{ secrets.GIST_TOKEN }}
          MY_GIST_ID: ${{ secrets.MY_GIST_ID }}
        run: python main.py
